#!/bin/bash

# Limpiar archivos temporales y de registro
rm -rf ~/.cache/*
sudo apt autoclean
sudo apt clean
sudo apt autoremove -y

# Deshabilitar aplicaciones de inicio innecesarias
gnome-session-properties

# Instalar y configurar zRam
sudo apt install -y zram-config

# Instalar Preload para mejorar el rendimiento de las aplicaciones
sudo apt install -y preload

# Optimizar la pila TCP
sudo sysctl -w net.ipv4.tcp_tw_reuse=1
sudo sysctl -w net.ipv4.tcp_fin_timeout=15

# Reducir el tiempo de espera de GRUB
sudo sed -i 's/GRUB_TIMEOUT=[0-9]*/GRUB_TIMEOUT=2/' /etc/default/grub
sudo update-grub

echo "Optimización completada. Por favor, reinicia tu sistema para aplicar los cambios."
